// <auto-generated />
namespace cuentasctacte_web_api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Pagos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pagos));
        
        string IMigrationMetadata.Id
        {
            get { return "202205272115222_Pagos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
