// <auto-generated />
namespace cuentasctacte_web_api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class personastipospersonas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(personastipospersonas));
        
        string IMigrationMetadata.Id
        {
            get { return "202204091844007_personas-tipos-personas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
